#!/usr/bin/env bash

sudo yum install -y git make gcc openssl-devel gcc-c++ patch readline readline-devel zlib zlib-devel libyaml-devel libffi-devel bzip2 autoconf automake libtool bison iconv-devel sqlite-devel ruby-devel
gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
wget https://get.rvm.io -O rvm.sh
bash ./rvm.sh stable --ruby=2.3.1
source /home/ec2-user/.profile
gem install bundler --no-rdoc --no-ri
git clone git://github.com/beefproject/beef.git
cd beef
bundle
