#!/usr/bin/env bash

sudo yum install -y git make gcc openssl-devel gcc-c++ patch readline readline-devel zlib zlib-devel libyaml-devel libffi-devel bzip2 autoconf automake libtool bison iconv-devel sqlite-devel
wget https://get.rvm.io -O rvm.sh
bash ./rvm.sh stable --ruby=1.9.3
source /home/ec2-user/.rvm/scripts/rvm
gem install bundler --no-rdoc --no-ri
git clone git://github.com/beefproject/beef.git
cd beef
bundle
